CREATE TABLE [Pelican].[Actual Fx curr_convert ] (
    [CURRENCY_CONVERSION_EXCHANGE_RATE_TYPE] NVARCHAR (MAX) NULL,
    [CURRENCY_CONVERSION_FROM_CURRENCY_CODE] NVARCHAR (MAX) NULL,
    [CURRENCY_CONVERSION_TO_CURRENCY_CODE]   NVARCHAR (MAX) NULL,
    [CURRENCY_CONVERSION_VALID_FROM_DATE]    NVARCHAR (MAX) NULL,
    [CURRENCY_CONVERSION_EXCHANGE_RATE]      NVARCHAR (MAX) NULL,
    [CURRENCY_CONVERSION_RATIO_FROM]         NVARCHAR (MAX) NULL,
    [CURRENCY_CONVERSION_RATIO_TO]           NVARCHAR (MAX) NULL
);

