CREATE TABLE [COMMON_DIMENSIONS].[BOOKING_STATUS_DIM] (
    [BOOKING_STATUS_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [BOOKING_STATUS_DESC] VARCHAR (20) NULL,
    CONSTRAINT [PK_BOOKING_STATUS_DIM] PRIMARY KEY CLUSTERED ([BOOKING_STATUS_ID] ASC)
);

