CREATE TABLE [COMMON_DIMENSIONS].[COUNTRY_DIM] (
    [COUNTRY_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [COUNTRY_ISO2_CODE] CHAR (2)      NULL,
    [COUNTRY_ISO3_CODE] CHAR (3)      NULL,
    [COUNTRY_CODE]      VARCHAR (50)  NULL,
    [COUNTRY_NAME]      VARCHAR (100) NULL,
    CONSTRAINT [PK_COUNTRY_DIM] PRIMARY KEY CLUSTERED ([COUNTRY_ID] ASC)
);

