CREATE TABLE [COMMON_DIMENSIONS].[CUSTOMER_DIM] (
    [CUSTOMER_ID]               INT           IDENTITY (1, 1) NOT NULL,
    [CUSTOMER_CODE]             VARCHAR (200) NULL,
    [CUSTOMER_NAME]             VARCHAR (100) NULL,
    [CUSTOMER_REFERENCE_NUMBER] VARCHAR (250) COLLATE Latin1_General_100_CI_AI_SC_UTF8 NULL,
    CONSTRAINT [PK_CUSTOMER_DIM] PRIMARY KEY CLUSTERED ([CUSTOMER_ID] ASC)
);

