CREATE TABLE [COMMON_DIMENSIONS].[INCOTERM_DIM] (
    [INCOTERM_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [INCOTERM]      VARCHAR (200) NULL,
    [INCOTERM_CITY] VARCHAR (100) NULL,
    CONSTRAINT [PK_INCOTERM_DIM] PRIMARY KEY CLUSTERED ([INCOTERM_ID] ASC)
);

