CREATE TABLE [COMMON_DIMENSIONS].[LOADING_TYPE_DIM] (
    [LOADING_TYPE_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [LOADING_TYPE_DESC] VARCHAR (50) NULL,
    CONSTRAINT [PK_LOADING_TYPE_DIM] PRIMARY KEY CLUSTERED ([LOADING_TYPE_ID] ASC)
);

