CREATE TABLE [COMMON_DIMENSIONS].[MATERIAL_DIM] (
    [MATERIAL_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [MATERIAL_NO]          VARCHAR (50)  NULL,
    [MATERIAL_DESCRIPTION] VARCHAR (150) NULL,
    CONSTRAINT [PK_MATERIAL_DIM] PRIMARY KEY CLUSTERED ([MATERIAL_ID] ASC)
);

