CREATE TABLE [COMMON_DIMENSIONS].[ORDER_TYPE_DIM] (
    [ORDER_TYPE_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [ORDER_TYPE_CODE] VARCHAR (100) NULL,
    CONSTRAINT [PK_ORDER_TYPE_DIM] PRIMARY KEY CLUSTERED ([ORDER_TYPE_ID] ASC)
);

