CREATE TABLE [COMMON_DIMENSIONS].[ROUTE_DIM] (
    [ROUTE_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [ROUTE_CODE] VARCHAR (100) NULL,
    CONSTRAINT [PK_ROUTE_DIM] PRIMARY KEY CLUSTERED ([ROUTE_ID] ASC)
);

