CREATE TABLE [COMMON_DIMENSIONS].[SHIPMENT_STATUS_DIM] (
    [SHIPMENT_STATUS_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [SHIPMENT_STATUS_DESC] VARCHAR (100) NULL,
    CONSTRAINT [PK_SHIPMENT_STATUS_DIM] PRIMARY KEY CLUSTERED ([SHIPMENT_STATUS_ID] ASC)
);

