CREATE TABLE [COMMON_DIMENSIONS].[SURCHARGE_STATUS_DIM] (
    [SURCHARGE_STATUS_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [SURCHARGE_STATUS_DESC] VARCHAR (50) NULL,
    CONSTRAINT [PK_SURCHARGE_STATUS_DIM] PRIMARY KEY CLUSTERED ([SURCHARGE_STATUS_ID] ASC)
);

