CREATE TABLE [GSAP].[COMPANY_TBL] (
    [COMPANY_CODE]     VARCHAR (25)  NULL,
    [COMPANY_NAME]     VARCHAR (100) NULL,
    [COMPANY_COUNTRY]  VARCHAR (100) NULL,
    [COMPANY_CURRENCY] VARCHAR (10)  NULL
);

