CREATE TABLE [GSAP].[COST_HEAD_TBL] (
    [OP_SEGMENT_LINE_ITEM]                VARCHAR (10) NULL,
    [OP_SEGMENT_LINE_ITEM_DESC]           VARCHAR (25) NULL,
    [OP_SEGMENT_LINE_ITEM_COST_HEAD_CODE] VARCHAR (20) NULL
);

