CREATE TABLE [GSAP].[ServiceType] (
    [COUNTRY_NAME]      VARCHAR (50)  NULL,
    [SFS_LINE_ITEM]     VARCHAR (50)  NULL,
    [ACCOUNT_NUMBER]    VARCHAR (25)  NULL,
    [COST_CENTER]       VARCHAR (20)  NULL,
    [VENDOR_NAME]       VARCHAR (200) NULL,
    [PLAN_ACTUAL]       VARCHAR (20)  NULL,
    [SERVICETYPE]       VARCHAR (50)  NULL,
    [WATERFALLCATEGORY] VARCHAR (25)  NULL
);

