CREATE TABLE [GSAP].[SUPPLY_VOLUME_PLAN_TBL] (
    [PLAN_ACTUAL]            VARCHAR (10) NULL,
    [COUNTRY_NAME]           VARCHAR (25) NULL,
    [PLAN_SUPPLY_VOL_PERIOD] VARCHAR (10) NULL,
    [PLAN_SUPPLY_VOL_TOTAL]  FLOAT (53)   NULL,
    [PLAN_SUPPLY_MONTH]      VARCHAR (3)  NULL,
    [PLAN_SUPPLY_YEAR]       VARCHAR (4)  NULL
);

