
CREATE PROCEDURE [dbo].[USP_MERGE_INCREMENTAL_DATA_PRC]

AS

BEGIN

BEGIN

MERGE TRANSPOREON_TMS.BOOKING_FACT_TBL AS TGT
USING
TRANSPOREON_TMS.BOOKING_FACT_STG AS STG
ON
TRIM(REPLACE(TGT.[TRANSPORT_NO],'*','')) = TRIM(REPLACE(STG.[TRANSPORT_NO],'*',''))
WHEN MATCHED AND 
TGT.[STATUS] 		<> 	STG.[STATUS] OR 
TGT.[TIMESTAMP]   	<>	STG.[TIMESTAMP] 
THEN
UPDATE SET 
 TGT.[BOOKING_START_DATE_ID] 				=	STG.[BOOKING_START_DATE_ID] 			
,TGT.[BOOKING_END_DATE_ID] 					=	STG.[BOOKING_END_DATE_ID] 				
,TGT.[BOOKING_START_TIME_ID] 				=	STG.[BOOKING_START_TIME_ID] 			
,TGT.[BOOKING_END_TIME_ID] 					=	STG.[BOOKING_END_TIME_ID] 				
,TGT.[BOOKING_CREATION_DATE_ID] 			=	STG.[BOOKING_CREATION_DATE_ID] 		
,TGT.[BOOKING_CREATION_TIME_ID] 			=	STG.[BOOKING_CREATION_TIME_ID] 		
,TGT.[BOOKING_STATUS_ID] 					=	STG.[BOOKING_STATUS_ID] 				
,TGT.[DISPATCH_STATUS_ARRIVAL_DATE_ID] 		=	STG.[DISPATCH_STATUS_ARRIVAL_DATE_ID] 	
,TGT.[DISPATCH_STATUS_ARRIVAL_TIME_ID] 		=	STG.[DISPATCH_STATUS_ARRIVAL_TIME_ID] 	
,TGT.[DISPATCH_STATUS_DEPARTURE_DATE_ID] 	=	STG.[DISPATCH_STATUS_DEPARTURE_DATE_ID] 
,TGT.[DISPATCH_STATUS_DEPARTURE_TIME_ID] 	=	STG.[DISPATCH_STATUS_DEPARTURE_TIME_ID] 
,TGT.[LOADING_TYPE_ID] 						=	STG.[LOADING_TYPE_ID] 					
,TGT.[LOCATION_NAME] 						=	STG.[LOCATION_NAME] 					
,TGT.[ADDED_BY_COMPANY] 					=	STG.[ADDED_BY_COMPANY] 				
,TGT.[GATE_DESC] 							=	STG.[GATE_DESC] 						
,TGT.[COMMENT] 								=	STG.[COMMENT] 							
,TGT.[VEHICLE_LICENCE_PLATE_NO] 			=	STG.[VEHICLE_LICENCE_PLATE_NO] 		
,TGT.[STATUS] 								=	STG.[STATUS] 							
,TGT.[TIMESTAMP] 							=	STG.[TIMESTAMP] 							

WHEN NOT MATCHED BY TARGET THEN
INSERT (
 [TRANSPORT_NO] 
,[BOOKING_START_DATE_ID] 			
,[BOOKING_END_DATE_ID] 				
,[BOOKING_START_TIME_ID] 			
,[BOOKING_END_TIME_ID] 				
,[BOOKING_CREATION_DATE_ID] 		
,[BOOKING_CREATION_TIME_ID] 		
,[BOOKING_STATUS_ID] 				
,[DISPATCH_STATUS_ARRIVAL_DATE_ID] 	
,[DISPATCH_STATUS_ARRIVAL_TIME_ID] 	
,[DISPATCH_STATUS_DEPARTURE_DATE_ID]
,[DISPATCH_STATUS_DEPARTURE_TIME_ID]
,[LOADING_TYPE_ID] 					
,[LOCATION_NAME] 					
,[ADDED_BY_COMPANY] 				
,[GATE_DESC] 						
,[COMMENT] 							
,[VEHICLE_LICENCE_PLATE_NO] 		
,[STATUS] 							
,[TIMESTAMP] )
VALUES (
TRIM(REPLACE(STG.[TRANSPORT_NO],'*',''))
,STG.[BOOKING_START_DATE_ID] 									
,STG.[BOOKING_END_DATE_ID] 				
,STG.[BOOKING_START_TIME_ID] 			
,STG.[BOOKING_END_TIME_ID] 				
,STG.[BOOKING_CREATION_DATE_ID] 		
,STG.[BOOKING_CREATION_TIME_ID] 		
,STG.[BOOKING_STATUS_ID] 				
,STG.[DISPATCH_STATUS_ARRIVAL_DATE_ID] 	
,STG.[DISPATCH_STATUS_ARRIVAL_TIME_ID] 	
,STG.[DISPATCH_STATUS_DEPARTURE_DATE_ID] 
,STG.[DISPATCH_STATUS_DEPARTURE_TIME_ID] 
,STG.[LOADING_TYPE_ID] 					
,STG.[LOCATION_NAME] 					
,STG.[ADDED_BY_COMPANY] 				
,STG.[GATE_DESC] 						
,STG.[COMMENT] 							
,STG.[VEHICLE_LICENCE_PLATE_NO] 		
,STG.[STATUS] 							
,STG.[TIMESTAMP] 	
)

WHEN NOT MATCHED BY SOURCE THEN DELETE;
END

BEGIN
MERGE TRANSPOREON_TMS.CARRIER_SURCHARGE_FACT_TBL AS TGT
USING
TRANSPOREON_TMS.CARRIER_SURCHARGE_FACT_STG AS STG
ON
TGT.[DELIVERY_NO]   = 		STG.[DELIVERY_NO] AND
TGT.[SURCHARGE_ID] 	=		STG.[SURCHARGE_ID] 
WHEN MATCHED AND 
TGT.[STATUS] 					<> 	STG.[STATUS] OR 
TGT.[TIMESTAMP]   				<>	STG.[TIMESTAMP] OR
TGT.[SURCHARGE_STATUS_ID] 		<>	STG.[SURCHARGE_STATUS_ID]
THEN
UPDATE SET 							
	 TGT.[TRANSPORT_NO] 						=		TRIM(REPLACE(STG.[TRANSPORT_NO],'*','')) 										
	,TGT.[SURCHARGE_SYSTEM_DATESTAMP_ID] 		=		STG.[SURCHARGE_SYSTEM_DATESTAMP_ID] 
	,TGT.[SURCHARGE_SYSTEM_TIMESTAMP_ID] 		=		STG.[SURCHARGE_SYSTEM_TIMESTAMP_ID] 
	,TGT.[SURCHARGE_PRICE] 						=		STG.[SURCHARGE_PRICE] 				
	,TGT.[SURCHARGE_CURRENCY_CODE] 				=		STG.[SURCHARGE_CURRENCY_CODE] 		
	,TGT.[SURCHARGE_DESC] 						=		STG.[SURCHARGE_DESC] 				
	,TGT.[SURCHARGE_STATUS_ID] 					=		STG.[SURCHARGE_STATUS_ID] 			
	,TGT.[SURCHARGE_NAME] 						=		STG.[SURCHARGE_NAME] 				
	,TGT.[COMPANY_NAME] 						=		STG.[COMPANY_NAME] 					
	,TGT.[REASON_DESC] 							=		STG.[REASON_DESC] 					
	,TGT.[SURCHARGE_LEVEL_DESC] 				=		STG.[SURCHARGE_LEVEL_DESC] 			
	,TGT.[STATUS] 								=		STG.[STATUS] 						
	,TGT.[TIMESTAMP] 							=		STG.[TIMESTAMP] 					
WHEN NOT MATCHED THEN
INSERT (
 [DELIVERY_NO] 								
,[TRANSPORT_NO] 				
,[SURCHARGE_ID] 				
,[SURCHARGE_SYSTEM_DATESTAMP_ID]
,[SURCHARGE_SYSTEM_TIMESTAMP_ID]
,[SURCHARGE_PRICE] 				
,[SURCHARGE_CURRENCY_CODE] 		
,[SURCHARGE_DESC] 				
,[SURCHARGE_STATUS_ID] 			
,[SURCHARGE_NAME] 				
,[COMPANY_NAME] 				
,[REASON_DESC] 					
,[SURCHARGE_LEVEL_DESC] 		
,[STATUS] 						
,[TIMESTAMP] )
VALUES (
 STG.[DELIVERY_NO] 										
,TRIM(REPLACE(STG.[TRANSPORT_NO],'*','')) 				
,STG.[SURCHARGE_ID] 				
,STG.[SURCHARGE_SYSTEM_DATESTAMP_ID]
,STG.[SURCHARGE_SYSTEM_TIMESTAMP_ID]
,STG.[SURCHARGE_PRICE] 				
,STG.[SURCHARGE_CURRENCY_CODE] 		
,STG.[SURCHARGE_DESC] 				
,STG.[SURCHARGE_STATUS_ID] 			
,STG.[SURCHARGE_NAME] 				
,STG.[COMPANY_NAME] 				
,STG.[REASON_DESC] 					
,STG.[SURCHARGE_LEVEL_DESC] 		
,STG.[STATUS] 						
,STG.[TIMESTAMP])

WHEN NOT MATCHED BY SOURCE THEN DELETE;	

END


BEGIN

MERGE TRANSPOREON_TMS.DELIVERY_DOCUMENT_FACT_TBL AS TGT
USING
TRANSPOREON_TMS.DELIVERY_DOCUMENT_FACT_STG AS STG
ON
TGT.[DELIVERY_NO]  = STG.[DELIVERY_NO] 
WHEN MATCHED AND 
TGT.[STATUS] 				<> 			STG.[STATUS] OR 
TGT.[TIMESTAMP]   			<>			STG.[TIMESTAMP] OR
TGT.[INCOTERM_ID] 			<>			STG.[INCOTERM_ID] OR
TGT.[SHIP_TO_ID] 			<>			STG.[SHIP_TO_ID] OR
TGT.[SHIPMENT_STATUS_ID] 	<>			STG.[SHIPMENT_STATUS_ID] OR					
TGT.[SOLD_TO_ID] 			<>			STG.[SOLD_TO_ID] OR
TGT.[ROUTE_ID] 				<>			STG.[ROUTE_ID] 
THEN
UPDATE SET 									
 TGT.[TRANSPORT_NO] 								=			TRIM(REPLACE(STG.TRANSPORT_NO,'*','')) 							
,TGT.[ACTUAL_DELIVERY_DATE_ID] 						=			STG.[ACTUAL_DELIVERY_DATE_ID] 				
,TGT.[ACTUAL_DELIVERY_TIME_ID] 						=			STG.[ACTUAL_DELIVERY_TIME_ID] 				
,TGT.[ACTUAL_LOADING_TIME] 							=			STG.[ACTUAL_LOADING_TIME] 					
,TGT.[ACTUAL_SHIPMENT_LOADING_DATE_ID] 				=			STG.[ACTUAL_SHIPMENT_LOADING_DATE_ID] 		
,TGT.[ACTUAL_SHIPMENT_LOADING_TIME_ID] 				=			STG.[ACTUAL_SHIPMENT_LOADING_TIME_ID] 		
,TGT.[COMMITTED_DELIVERY_DATE_ID] 					=			STG.[COMMITTED_DELIVERY_DATE_ID] 			
,TGT.[COMMITTED_DELIVERY_TIME_ID] 					=			STG.[COMMITTED_DELIVERY_TIME_ID] 			
,TGT.[CUSTOMER_DELIVERY_WINDOW] 					=			STG.[CUSTOMER_DELIVERY_WINDOW] 				
,TGT.[DELIVERY_CREATED_DATE_ID] 					=			STG.[DELIVERY_CREATED_DATE_ID] 				
,TGT.[DELIVERY_CREATED_TIME_ID] 					=			STG.[DELIVERY_CREATED_TIME_ID] 				
,TGT.[DELIVERY_PRICE] 								=			TRIM(REPLACE(STG.[DELIVERY_PRICE],',','')) 						
,TGT.[DELIVERY_DISTANCE] 							=			TRIM(REPLACE(STG.[DELIVERY_DISTANCE],',','')) 	 					
,TGT.[DISTANCE_UOM] 								=			STG.[DISTANCE_UOM] 							
,TGT.[INCOTERM_ID] 									=			STG.[INCOTERM_ID] 							
,TGT.[LOADING_POSSIBLE_FROM_DATE_ID] 				=			STG.[LOADING_POSSIBLE_FROM_DATE_ID] 		
,TGT.[LOADING_POSSIBLE_FROM_TIME_ID] 				=			STG.[LOADING_POSSIBLE_FROM_TIME_ID] 		
,TGT.[LOADING_POSSIBLE_TO_DATE_ID] 					=			STG.[LOADING_POSSIBLE_TO_DATE_ID] 			
,TGT.[LOADING_POSSIBLE_TO_TIME] 					=			STG.[LOADING_POSSIBLE_TO_TIME] 				
,TGT.[LOADING_STATION_COUNTRY_ID] 					=			STG.[LOADING_STATION_COUNTRY_ID] 			
,TGT.[LOADING_STATION_CODE] 						=			STG.[LOADING_STATION_CODE] 					
,TGT.[PLANNED_DELIVERY_DATE_ID] 					=			STG.[PLANNED_DELIVERY_DATE_ID] 				
,TGT.[PLANNED_DELIVERY_TIME_ID] 					=			STG.[PLANNED_DELIVERY_TIME_ID] 				
,TGT.[PLANNED_SHIPMENT_LOADING_DATE_ID] 			=			STG.[PLANNED_SHIPMENT_LOADING_DATE_ID] 		
,TGT.[PLANNED_SHIPMENT_LOADING_TIME_ID] 			=			STG.[PLANNED_SHIPMENT_LOADING_TIME_ID] 		
,TGT.[SCHEDULING_UNIT_DESC] 						=			STG.[SCHEDULING_UNIT_DESC] 					
,TGT.[SHIP_TO_ID] 									=			STG.[SHIP_TO_ID] 							
,TGT.[SHIPMENT_STATUS_ID] 							=			STG.[SHIPMENT_STATUS_ID] 					
,TGT.[SOLD_TO_ID] 									=			STG.[SOLD_TO_ID] 							
,TGT.[STACKABLE_IND] 								=			STG.[STACKABLE_IND] 						
,TGT.[TRANSPORTATION_PLANNING_POINT] 				=			STG.[TRANSPORTATION_PLANNING_POINT] 		
,TGT.[UNLOADING_POSSIBLE_FROM_DATE_ID] 				=			STG.[UNLOADING_POSSIBLE_FROM_DATE_ID] 		
,TGT.[UNLOADING_POSSIBLE_FROM_TIME_ID] 				=			STG.[UNLOADING_POSSIBLE_FROM_TIME_ID] 		
,TGT.[UNLOADING_POSSIBLE_TO_DATE_ID] 				=			STG.[UNLOADING_POSSIBLE_TO_DATE_ID] 		
,TGT.[UNLOADING_POSSIBLE_TO_TIME_ID] 				=			STG.[UNLOADING_POSSIBLE_TO_TIME_ID] 		
,TGT.[DELIVERED_VOLUME] 							=			TRIM(REPLACE(STG.[DELIVERED_VOLUME],',','')) 						
,TGT.[VOLUME_UOM] 									=			STG.[VOLUME_UOM] 											
,TGT.[DELIVERED_WEIGHT] 							=			TRIM(REPLACE(STG.[DELIVERED_WEIGHT],',','')) 						
,TGT.[WEIGHT_UOM] 									=			STG.[WEIGHT_UOM] 											
,TGT.[BASE_PRICE] 									=			TRIM(REPLACE(STG.[BASE_PRICE],',','')) 							
,TGT.[EXTRA_COST_1] 								=			STG.[EXTRA_COST_1] 							
,TGT.[EXTRA_COST_2] 								=			STG.[EXTRA_COST_2] 							
,TGT.[EXTRA_COST_3] 								=			STG.[EXTRA_COST_3] 							
,TGT.[EXTRA_COST_4] 								=			STG.[EXTRA_COST_4] 							
,TGT.[EXTRA_COST_5] 								=			STG.[EXTRA_COST_5] 							
,TGT.[EXTRA_COST_6] 								=			STG.[EXTRA_COST_6] 							
,TGT.[EXTRA_COST_7] 								=			STG.[EXTRA_COST_7] 							
,TGT.[EXTRA_COST_8] 								=			STG.[EXTRA_COST_8] 							
,TGT.[EXTRA_COST_9] 								=			STG.[EXTRA_COST_9] 							
,TGT.[EXTRA_COST_10] 								=			STG.[EXTRA_COST_10] 						
,TGT.[EXTRA_COST_11] 								=			STG.[EXTRA_COST_11] 						
,TGT.[EXTRA_COST_12] 								=			STG.[EXTRA_COST_12] 						
,TGT.[EXTRA_COST_13] 								=			STG.[EXTRA_COST_13] 						
,TGT.[EXTRA_COST_14] 								=			STG.[EXTRA_COST_14] 						
,TGT.[EXTRA_COST_15] 								=			STG.[EXTRA_COST_15] 						
,TGT.[EXTRA_COST_16] 								=			STG.[EXTRA_COST_16] 						
,TGT.[EXTRA_COST_17] 								=			STG.[EXTRA_COST_17] 						
,TGT.[EXTRA_COST_18] 								=			STG.[EXTRA_COST_18] 						
,TGT.[EXTRA_COST_1_UNIT] 							=			STG.[EXTRA_COST_1_UNIT] 					
,TGT.[EXTRA_COST_2_UNIT] 							=			STG.[EXTRA_COST_2_UNIT] 					
,TGT.[EXTRA_COST_3_UNIT] 							=			STG.[EXTRA_COST_3_UNIT] 					
,TGT.[EXTRA_COST_4_UNIT] 							=			STG.[EXTRA_COST_4_UNIT] 					
,TGT.[EXTRA_COST_1_DESCRIPTION] 					=			STG.[EXTRA_COST_1_DESCRIPTION] 				
,TGT.[EXTRA_COST_2_DESCRIPTION] 					=			STG.[EXTRA_COST_2_DESCRIPTION] 				
,TGT.[EXTRA_COST_3_DESCRIPTION] 					=			STG.[EXTRA_COST_3_DESCRIPTION] 				
,TGT.[EXTRA_COST_4_DESCRIPTION] 					=			STG.[EXTRA_COST_4_DESCRIPTION] 				
,TGT.[EXTRA_COST_5_DESCRIPTION] 					=			STG.[EXTRA_COST_5_DESCRIPTION] 				
,TGT.[EXTRA_COST_6_DESCRIPTION] 					=			STG.[EXTRA_COST_6_DESCRIPTION] 				
,TGT.[EXTRA_COST_7_DESCRIPTION] 					=			STG.[EXTRA_COST_7_DESCRIPTION] 				
,TGT.[EXTRA_COST_8_DESCRIPTION] 					=			STG.[EXTRA_COST_8_DESCRIPTION] 				
,TGT.[EXTRA_COST_9_DESCRIPTION] 					=			STG.[EXTRA_COST_9_DESCRIPTION] 				
,TGT.[EXTRA_COST_10_DESCRIPTION] 					=			STG.[EXTRA_COST_10_DESCRIPTION] 			
,TGT.[EXTRA_COST_11_DESCRIPTION] 					=			STG.[EXTRA_COST_11_DESCRIPTION] 			
,TGT.[EXTRA_COST_12_DESCRIPTION] 					=			STG.[EXTRA_COST_12_DESCRIPTION] 			
,TGT.[EXTRA_COST_13_DESCRIPTION] 					=			STG.[EXTRA_COST_13_DESCRIPTION] 			
,TGT.[EXTRA_COST_14_DESCRIPTION] 					=			STG.[EXTRA_COST_14_DESCRIPTION] 			
,TGT.[EXTRA_COST_15_DESCRIPTION] 					=			STG.[EXTRA_COST_15_DESCRIPTION] 			
,TGT.[EXTRA_COST_16_DESCRIPTION] 					=			STG.[EXTRA_COST_16_DESCRIPTION] 			
,TGT.[EXTRA_COST_17_DESCRIPTION] 					=			STG.[EXTRA_COST_17_DESCRIPTION] 			
,TGT.[EXTRA_COST_18_DESCRIPTION] 					=			STG.[EXTRA_COST_18_DESCRIPTION] 			
,TGT.[ADDITIONAL_COST_FIXED] 						=			TRIM(REPLACE(STG.[ADDITIONAL_COST_FIXED],',',''))			
,TGT.[ADDITIONAL_COST_PER_TON] 						=			TRIM(REPLACE(STG.[ADDITIONAL_COST_PER_TON],',',''))				
,TGT.[ADDITIONAL_COST_DIFF_PRICE] 					=			TRIM(REPLACE(STG.[ADDITIONAL_COST_DIFF_PRICE],',',''))			
,TGT.[ADDITIONAL_COST_BASIC_PRICE] 					=			TRIM(REPLACE(STG.[ADDITIONAL_COST_BASIC_PRICE],',',''))			
,TGT.[DROP_OFF_COST] 								=			TRIM(REPLACE(STG.[DROP_OFF_COST],',',''))			
,TGT.[ADD_COST_PER_KG_DELIVERY_DHL] 				=			TRIM(REPLACE(STG.[ADD_COST_PER_KG_DELIVERY_DHL],',',''))			
,TGT.[ADD_COST_FIXED_DELIVERY_DHL] 					=			TRIM(REPLACE(STG.[ADD_COST_FIXED_DELIVERY_DHL],',',''))			
,TGT.[ADD_COST_PER_KG_TRANSPORT_DHL] 				=			TRIM(REPLACE(STG.[ADD_COST_PER_KG_TRANSPORT_DHL],',','')) 			
,TGT.[ADD_COST_FIXED_TRANSPORT_DHL] 				=			TRIM(REPLACE(STG.[ADD_COST_FIXED_TRANSPORT_DHL],',',''))			
,TGT.[BURSPED_DP03_05_SURCHARGE] 					=			STG.[BURSPED_DP03_05_SURCHARGE] 			
,TGT.[LOADING_STATION_COMPANY_NAME] 				=			STG.[LOADING_STATION_COMPANY_NAME] 			
,TGT.[UNLOADING_STATION_POSTAL_CODE] 				=			STG.[UNLOADING_STATION_POSTAL_CODE] 		
,TGT.[UNLOADING_STATION_CITY] 						=			STG.[UNLOADING_STATION_CITY] 				
,TGT.[UNLOADING_STATION_CODE] 						=			STG.[UNLOADING_STATION_CODE] 				
,TGT.[UNLOADING_STATION_DESC] 						=			STG.[UNLOADING_STATION_DESC] 				
,TGT.[LOADING_STATION_POSTAL_CODE] 					=			STG.[LOADING_STATION_POSTAL_CODE] 			
,TGT.[LOADING_STATION_CITY] 						=			STG.[LOADING_STATION_CITY] 					
,TGT.[UNLOADING_STATION_COMPANY_NAME] 				=			STG.[UNLOADING_STATION_COMPANY_NAME] 		
,TGT.[UNLOADING_STATION_STREET_NO] 					=			STG.[UNLOADING_STATION_STREET_NO] 			
,TGT.[UNLOADING_STATION_COUNTRY_ID] 				=			STG.[UNLOADING_STATION_COUNTRY_ID] 			
,TGT.[LENGTH] 										=			TRIM(REPLACE(STG.[LENGTH],',','')) 								
,TGT.[LENGTH_UNIT] 									=			STG.[LENGTH_UNIT] 							
,TGT.[ORDER_TYPE_ID] 								=			STG.[ORDER_TYPE_ID] 						
,TGT.[ROUTE_ID] 									=			STG.[ROUTE_ID] 								
,TGT.[DELIVERY_TERM_CODE] 							=			STG.[DELIVERY_TERM_CODE] 					
,TGT.[DELIVERY_PRIORITY_CODE] 						=			STG.[DELIVERY_PRIORITY_CODE] 				
,TGT.[SHIP_TO_NAME] 								=			STG.[SHIP_TO_NAME] 							
,TGT.[SALES_ORDER_NUMBER] 							=			STG.[SALES_ORDER_NUMBER] 					
,TGT.[SALES_OFFICE_ID] 								=			STG.[SALES_OFFICE_ID] 						
,TGT.[COUNT_PLANNED_DELIVERY_DATE] 					=			STG.[COUNT_PLANNED_DELIVERY_DATE] 			
,TGT.[ORIGINAL_UNLOADING_TO_TIME_ID] 				=			STG.[ORIGINAL_UNLOADING_TO_TIME_ID] 		
,TGT.[ORIGINAL_LOADING_FROM_DATE_ID] 				=			STG.[ORIGINAL_LOADING_FROM_DATE_ID] 		
,TGT.[ORIGINAL_LOADING_FROM_TIME_ID] 				=			STG.[ORIGINAL_LOADING_FROM_TIME_ID] 		
,TGT.[ORIGINAL_LOADING_TO_DATE_ID] 					=			STG.[ORIGINAL_LOADING_TO_DATE_ID] 			
,TGT.[ORIGINAL_LOADING_TO_TIME_ID] 					=			STG.[ORIGINAL_LOADING_TO_TIME_ID] 			
,TGT.[ORIGINAL_STORAGE_POSITION] 					=			STG.[ORIGINAL_STORAGE_POSITION] 			
,TGT.[ORIGINAL_STORAGE_POSITION_UNIT] 				=			STG.[ORIGINAL_STORAGE_POSITION_UNIT] 		
,TGT.[ORIGINAL_UNLOADING_FROM_DATE_ID] 				=			STG.[ORIGINAL_UNLOADING_FROM_DATE_ID] 		
,TGT.[ORIGINAL_UNLOADING_FROM_TIME_ID] 				=			STG.[ORIGINAL_UNLOADING_FROM_TIME_ID] 		
,TGT.[ORIGINAL_UNLOADING_TO_DATE_ID] 				=			STG.[ORIGINAL_UNLOADING_TO_DATE_ID] 		
,TGT.[ORIGINAL_VOLUME] 								=			TRIM(REPLACE(STG.[ORIGINAL_VOLUME],',','')) 				
,TGT.[ORIGINAL_VOLUME_UOM] 							=			STG.[ORIGINAL_VOLUME_UOM] 								
,TGT.[ORIGINAL_WEIGHT] 								=			TRIM(REPLACE(STG.[ORIGINAL_WEIGHT],',','')) 				
,TGT.[ORIGINAL_WEIGHT_UOM] 							=			STG.[ORIGINAL_WEIGHT_UOM] 					
,TGT.[LOADING_STATION_LATITUDE] 					=			STG.[LOADING_STATION_LATITUDE] 				
,TGT.[LOADING_STATION_LONGITUDE] 					=			STG.[LOADING_STATION_LONGITUDE] 			
,TGT.[UNLOADING_STATION_LATITUDE] 					=			STG.[UNLOADING_STATION_LATITUDE] 			
,TGT.[UNLOADING_STATION_LONGITUDE] 					=			STG.[UNLOADING_STATION_LONGITUDE] 			
,TGT.[STATUS] 										=			STG.[STATUS] 								
,TGT.[TIMESTAMP] 									=			STG.[TIMESTAMP] 	
						
WHEN NOT MATCHED THEN
INSERT (
[DELIVERY_NO] 						
,[TRANSPORT_NO] 						
,[ACTUAL_DELIVERY_DATE_ID] 			
,[ACTUAL_DELIVERY_TIME_ID] 			
,[ACTUAL_LOADING_TIME] 				
,[ACTUAL_SHIPMENT_LOADING_DATE_ID] 	
,[ACTUAL_SHIPMENT_LOADING_TIME_ID] 	
,[COMMITTED_DELIVERY_DATE_ID] 		
,[COMMITTED_DELIVERY_TIME_ID] 		
,[CUSTOMER_DELIVERY_WINDOW] 			
,[DELIVERY_CREATED_DATE_ID] 			
,[DELIVERY_CREATED_TIME_ID] 			
,[DELIVERY_PRICE] 					
,[DELIVERY_DISTANCE] 				
,[DISTANCE_UOM] 						
,[INCOTERM_ID] 						
,[LOADING_POSSIBLE_FROM_DATE_ID] 	
,[LOADING_POSSIBLE_FROM_TIME_ID] 	
,[LOADING_POSSIBLE_TO_DATE_ID] 		
,[LOADING_POSSIBLE_TO_TIME] 			
,[LOADING_STATION_COUNTRY_ID] 		
,[LOADING_STATION_CODE] 				
,[PLANNED_DELIVERY_DATE_ID] 			
,[PLANNED_DELIVERY_TIME_ID] 			
,[PLANNED_SHIPMENT_LOADING_DATE_ID] 	
,[PLANNED_SHIPMENT_LOADING_TIME_ID] 	
,[SCHEDULING_UNIT_DESC] 				
,[SHIP_TO_ID] 						
,[SHIPMENT_STATUS_ID] 				
,[SOLD_TO_ID] 						
,[STACKABLE_IND] 					
,[TRANSPORTATION_PLANNING_POINT] 	
,[UNLOADING_POSSIBLE_FROM_DATE_ID] 	
,[UNLOADING_POSSIBLE_FROM_TIME_ID] 	
,[UNLOADING_POSSIBLE_TO_DATE_ID] 	
,[UNLOADING_POSSIBLE_TO_TIME_ID] 	
,[DELIVERED_VOLUME] 					
,[VOLUME_UOM] 						
,[DELIVERED_WEIGHT] 					
,[WEIGHT_UOM] 						
,[BASE_PRICE] 						
,[EXTRA_COST_1] 						
,[EXTRA_COST_2] 						
,[EXTRA_COST_3] 						
,[EXTRA_COST_4] 						
,[EXTRA_COST_5] 						
,[EXTRA_COST_6] 						
,[EXTRA_COST_7] 						
,[EXTRA_COST_8] 						
,[EXTRA_COST_9] 						
,[EXTRA_COST_10] 					
,[EXTRA_COST_11] 					
,[EXTRA_COST_12] 					
,[EXTRA_COST_13] 					
,[EXTRA_COST_14] 					
,[EXTRA_COST_15] 					
,[EXTRA_COST_16] 					
,[EXTRA_COST_17] 					
,[EXTRA_COST_18] 					
,[EXTRA_COST_1_UNIT] 				
,[EXTRA_COST_2_UNIT] 				
,[EXTRA_COST_3_UNIT] 				
,[EXTRA_COST_4_UNIT] 				
,[EXTRA_COST_1_DESCRIPTION] 			
,[EXTRA_COST_2_DESCRIPTION] 			
,[EXTRA_COST_3_DESCRIPTION] 			
,[EXTRA_COST_4_DESCRIPTION] 			
,[EXTRA_COST_5_DESCRIPTION] 			
,[EXTRA_COST_6_DESCRIPTION] 			
,[EXTRA_COST_7_DESCRIPTION] 			
,[EXTRA_COST_8_DESCRIPTION] 			
,[EXTRA_COST_9_DESCRIPTION] 			
,[EXTRA_COST_10_DESCRIPTION] 		
,[EXTRA_COST_11_DESCRIPTION] 		
,[EXTRA_COST_12_DESCRIPTION] 		
,[EXTRA_COST_13_DESCRIPTION] 		
,[EXTRA_COST_14_DESCRIPTION] 		
,[EXTRA_COST_15_DESCRIPTION] 		
,[EXTRA_COST_16_DESCRIPTION] 		
,[EXTRA_COST_17_DESCRIPTION] 		
,[EXTRA_COST_18_DESCRIPTION] 		
,[ADDITIONAL_COST_FIXED] 			
,[ADDITIONAL_COST_PER_TON] 			
,[ADDITIONAL_COST_DIFF_PRICE] 		
,[ADDITIONAL_COST_BASIC_PRICE] 		
,[DROP_OFF_COST] 					
,[ADD_COST_PER_KG_DELIVERY_DHL] 		
,[ADD_COST_FIXED_DELIVERY_DHL] 		
,[ADD_COST_PER_KG_TRANSPORT_DHL] 	
,[ADD_COST_FIXED_TRANSPORT_DHL] 		
,[BURSPED_DP03_05_SURCHARGE] 		
,[LOADING_STATION_COMPANY_NAME] 		
,[UNLOADING_STATION_POSTAL_CODE] 	
,[UNLOADING_STATION_CITY] 			
,[UNLOADING_STATION_CODE] 			
,[UNLOADING_STATION_DESC] 			
,[LOADING_STATION_POSTAL_CODE] 		
,[LOADING_STATION_CITY] 				
,[UNLOADING_STATION_COMPANY_NAME] 	
,[UNLOADING_STATION_STREET_NO] 		
,[UNLOADING_STATION_COUNTRY_ID] 		
,[LENGTH] 							
,[LENGTH_UNIT] 						
,[ORDER_TYPE_ID] 					
,[ROUTE_ID] 							
,[DELIVERY_TERM_CODE] 				
,[DELIVERY_PRIORITY_CODE] 			
,[SHIP_TO_NAME] 						
,[SALES_ORDER_NUMBER] 				
,[SALES_OFFICE_ID] 					
,[COUNT_PLANNED_DELIVERY_DATE] 		
,[ORIGINAL_UNLOADING_TO_TIME_ID] 	
,[ORIGINAL_LOADING_FROM_DATE_ID] 	
,[ORIGINAL_LOADING_FROM_TIME_ID] 	
,[ORIGINAL_LOADING_TO_DATE_ID] 		
,[ORIGINAL_LOADING_TO_TIME_ID] 		
,[ORIGINAL_STORAGE_POSITION] 		
,[ORIGINAL_STORAGE_POSITION_UNIT] 	
,[ORIGINAL_UNLOADING_FROM_DATE_ID] 	
,[ORIGINAL_UNLOADING_FROM_TIME_ID] 	
,[ORIGINAL_UNLOADING_TO_DATE_ID] 	
,[ORIGINAL_VOLUME] 					
,[ORIGINAL_VOLUME_UOM] 				
,[ORIGINAL_WEIGHT] 					
,[ORIGINAL_WEIGHT_UOM] 				
,[LOADING_STATION_LATITUDE] 			
,[LOADING_STATION_LONGITUDE] 		
,[UNLOADING_STATION_LATITUDE] 		
,[UNLOADING_STATION_LONGITUDE] 		
,[STATUS] 							
,[TIMESTAMP] 						
)
VALUES (
STG.[DELIVERY_NO] 						
,TRIM(REPLACE(STG.TRANSPORT_NO,'*','')) 						
,STG.[ACTUAL_DELIVERY_DATE_ID] 			
,STG.[ACTUAL_DELIVERY_TIME_ID] 			
,STG.[ACTUAL_LOADING_TIME] 				
,STG.[ACTUAL_SHIPMENT_LOADING_DATE_ID] 	
,STG.[ACTUAL_SHIPMENT_LOADING_TIME_ID] 	
,STG.[COMMITTED_DELIVERY_DATE_ID] 		
,STG.[COMMITTED_DELIVERY_TIME_ID] 		
,STG.[CUSTOMER_DELIVERY_WINDOW] 			
,STG.[DELIVERY_CREATED_DATE_ID] 			
,STG.[DELIVERY_CREATED_TIME_ID] 			
,TRIM(REPLACE(STG.[DELIVERY_PRICE],',','')) 					
,TRIM(REPLACE(STG.[DELIVERY_DISTANCE],',','')) 				
,STG.[DISTANCE_UOM] 						
,STG.[INCOTERM_ID] 						
,STG.[LOADING_POSSIBLE_FROM_DATE_ID] 	
,STG.[LOADING_POSSIBLE_FROM_TIME_ID] 	
,STG.[LOADING_POSSIBLE_TO_DATE_ID] 		
,STG.[LOADING_POSSIBLE_TO_TIME] 			
,STG.[LOADING_STATION_COUNTRY_ID] 		
,STG.[LOADING_STATION_CODE] 				
,STG.[PLANNED_DELIVERY_DATE_ID] 			
,STG.[PLANNED_DELIVERY_TIME_ID] 			
,STG.[PLANNED_SHIPMENT_LOADING_DATE_ID] 	
,STG.[PLANNED_SHIPMENT_LOADING_TIME_ID] 	
,STG.[SCHEDULING_UNIT_DESC] 				
,STG.[SHIP_TO_ID] 						
,STG.[SHIPMENT_STATUS_ID] 				
,STG.[SOLD_TO_ID] 						
,STG.[STACKABLE_IND] 					
,STG.[TRANSPORTATION_PLANNING_POINT] 	
,STG.[UNLOADING_POSSIBLE_FROM_DATE_ID] 	
,STG.[UNLOADING_POSSIBLE_FROM_TIME_ID] 	
,STG.[UNLOADING_POSSIBLE_TO_DATE_ID] 	
,STG.[UNLOADING_POSSIBLE_TO_TIME_ID] 	
,TRIM(REPLACE(STG.[DELIVERED_VOLUME],',','')) 					
,STG.[VOLUME_UOM] 						
,TRIM(REPLACE(STG.[DELIVERED_WEIGHT],',','')) 					
,STG.[WEIGHT_UOM] 						
,TRIM(REPLACE(STG.[BASE_PRICE],',','')) 						
,STG.[EXTRA_COST_1] 						
,STG.[EXTRA_COST_2] 						
,STG.[EXTRA_COST_3] 						
,STG.[EXTRA_COST_4] 						
,STG.[EXTRA_COST_5] 						
,STG.[EXTRA_COST_6] 						
,STG.[EXTRA_COST_7] 						
,STG.[EXTRA_COST_8] 						
,STG.[EXTRA_COST_9] 						
,STG.[EXTRA_COST_10] 					
,STG.[EXTRA_COST_11] 					
,STG.[EXTRA_COST_12] 					
,STG.[EXTRA_COST_13] 					
,STG.[EXTRA_COST_14] 					
,STG.[EXTRA_COST_15] 					
,STG.[EXTRA_COST_16] 					
,STG.[EXTRA_COST_17] 					
,STG.[EXTRA_COST_18] 					
,STG.[EXTRA_COST_1_UNIT] 				
,STG.[EXTRA_COST_2_UNIT] 				
,STG.[EXTRA_COST_3_UNIT] 				
,STG.[EXTRA_COST_4_UNIT] 				
,STG.[EXTRA_COST_1_DESCRIPTION] 			
,STG.[EXTRA_COST_2_DESCRIPTION] 			
,STG.[EXTRA_COST_3_DESCRIPTION] 			
,STG.[EXTRA_COST_4_DESCRIPTION] 			
,STG.[EXTRA_COST_5_DESCRIPTION] 			
,STG.[EXTRA_COST_6_DESCRIPTION] 			
,STG.[EXTRA_COST_7_DESCRIPTION] 			
,STG.[EXTRA_COST_8_DESCRIPTION] 			
,STG.[EXTRA_COST_9_DESCRIPTION] 			
,STG.[EXTRA_COST_10_DESCRIPTION] 		
,STG.[EXTRA_COST_11_DESCRIPTION] 		
,STG.[EXTRA_COST_12_DESCRIPTION] 		
,STG.[EXTRA_COST_13_DESCRIPTION] 		
,STG.[EXTRA_COST_14_DESCRIPTION] 		
,STG.[EXTRA_COST_15_DESCRIPTION] 		
,STG.[EXTRA_COST_16_DESCRIPTION] 		
,STG.[EXTRA_COST_17_DESCRIPTION] 		
,STG.[EXTRA_COST_18_DESCRIPTION] 		
,TRIM(REPLACE(STG.[ADDITIONAL_COST_FIXED],',',''))	
,TRIM(REPLACE(STG.[ADDITIONAL_COST_PER_TON],',',''))		
,TRIM(REPLACE(STG.[ADDITIONAL_COST_DIFF_PRICE],',',''))	
,TRIM(REPLACE(STG.[ADDITIONAL_COST_BASIC_PRICE],',',''))		
,TRIM(REPLACE(STG.[DROP_OFF_COST],',',''))	
,TRIM(REPLACE(STG.[ADD_COST_PER_KG_DELIVERY_DHL],',',''))		
,TRIM(REPLACE(STG.[ADD_COST_FIXED_DELIVERY_DHL],',',''))		
,TRIM(REPLACE(STG.[ADD_COST_PER_KG_TRANSPORT_DHL],',','')) 	
,TRIM(REPLACE(STG.[ADD_COST_FIXED_TRANSPORT_DHL],',',''))		
,STG.[BURSPED_DP03_05_SURCHARGE] 		
,STG.[LOADING_STATION_COMPANY_NAME] 		
,STG.[UNLOADING_STATION_POSTAL_CODE] 	
,STG.[UNLOADING_STATION_CITY] 			
,STG.[UNLOADING_STATION_CODE] 			
,STG.[UNLOADING_STATION_DESC] 			
,STG.[LOADING_STATION_POSTAL_CODE] 		
,STG.[LOADING_STATION_CITY] 				
,STG.[UNLOADING_STATION_COMPANY_NAME] 	
,STG.[UNLOADING_STATION_STREET_NO] 		
,STG.[UNLOADING_STATION_COUNTRY_ID] 		
,TRIM(REPLACE(STG.[LENGTH],',','')) 							
,STG.[LENGTH_UNIT] 						
,STG.[ORDER_TYPE_ID] 					
,STG.[ROUTE_ID] 							
,STG.[DELIVERY_TERM_CODE] 				
,STG.[DELIVERY_PRIORITY_CODE] 			
,STG.[SHIP_TO_NAME] 						
,STG.[SALES_ORDER_NUMBER] 				
,STG.[SALES_OFFICE_ID] 					
,STG.[COUNT_PLANNED_DELIVERY_DATE] 		
,STG.[ORIGINAL_UNLOADING_TO_TIME_ID] 	
,STG.[ORIGINAL_LOADING_FROM_DATE_ID] 	
,STG.[ORIGINAL_LOADING_FROM_TIME_ID] 	
,STG.[ORIGINAL_LOADING_TO_DATE_ID] 		
,STG.[ORIGINAL_LOADING_TO_TIME_ID] 		
,STG.[ORIGINAL_STORAGE_POSITION] 		
,STG.[ORIGINAL_STORAGE_POSITION_UNIT] 	
,STG.[ORIGINAL_UNLOADING_FROM_DATE_ID] 	
,STG.[ORIGINAL_UNLOADING_FROM_TIME_ID] 	
,STG.[ORIGINAL_UNLOADING_TO_DATE_ID] 	
,TRIM(REPLACE(STG.[ORIGINAL_VOLUME],',','')) 					
,STG.[ORIGINAL_VOLUME_UOM] 				
,TRIM(REPLACE(STG.[ORIGINAL_WEIGHT],',','')) 					
,STG.[ORIGINAL_WEIGHT_UOM] 				
,STG.[LOADING_STATION_LATITUDE] 			
,STG.[LOADING_STATION_LONGITUDE] 		
,STG.[UNLOADING_STATION_LATITUDE] 		
,STG.[UNLOADING_STATION_LONGITUDE] 		
,STG.[STATUS] 							
,STG.[TIMESTAMP] 						
)

WHEN NOT MATCHED BY SOURCE THEN DELETE;

END

BEGIN

MERGE TRANSPOREON_TMS.DELIVERY_ITEM_FACT_TBL AS TGT
USING
TRANSPOREON_TMS.DELIVERY_ITEM_FACT_STG AS STG
ON
TGT.[DELIVERY_NO]  			= 		STG.[DELIVERY_NO] AND
TGT.[DELIVERY_ITEM_NO] 		=		STG.[DELIVERY_ITEM_NO] 
WHEN MATCHED AND 
TGT.[STATUS] 		<> 	STG.[STATUS] OR 
TGT.[TIMESTAMP]   	<>	STG.[TIMESTAMP] 
THEN
UPDATE SET 	
 TGT.[TRANSPORT_NO] 							=		TRIM(REPLACE(STG.TRANSPORT_NO,'*','')) 					
,TGT.[MATERIAL_ID] 								=		STG.[MATERIAL_ID] 					
,TGT.[PLANNED_STORAGE_POSITIONS_QTY] 			=		TRIM(REPLACE(STG.[PLANNED_STORAGE_POSITIONS_QTY],',','')) 
,TGT.[PLANNED_NET_WEIGHT] 						=		TRIM(REPLACE(STG.[PLANNED_NET_WEIGHT],',',''))  			
,TGT.[PLANNED_GROSS_WEIGHT] 					=		TRIM(REPLACE(STG.[PLANNED_GROSS_WEIGHT],',',''))  			
,TGT.[PLANNED_VOLUME] 							=		TRIM(REPLACE(STG.[PLANNED_VOLUME],',',''))  				
,TGT.[ACTUAL_STORAGE_POSITIONS_QTY] 			=		TRIM(REPLACE(STG.[ACTUAL_STORAGE_POSITIONS_QTY] ,',','')) 
,TGT.[HZG_UN_NO] 								=		STG.[HZG_UN_NO] 					
,TGT.[PALLET_INFORMATION] 						=		STG.[PALLET_INFORMATION] 			
,TGT.[BATCH_NO] 								=		STG.[BATCH_NO] 						
,TGT.[HAZARDOUS_GOODS_INFORMATION] 				=		STG.[HAZARDOUS_GOODS_INFORMATION] 	
,TGT.[HAZARDOUS_GOODS_CLASS] 					=		STG.[HAZARDOUS_GOODS_CLASS] 		
,TGT.[PACKAGING_ITEMS_QTY] 						=		TRIM(REPLACE(STG.[PACKAGING_ITEMS_QTY],',','')) 			
,TGT.[VOLUME_PER_PACKAGE] 						=		TRIM(REPLACE(STG.[VOLUME_PER_PACKAGE] ,',','')) 			
,TGT.[HAZARDOUS_GOOD_PACKAGING_GROUP]			=		STG.[HAZARDOUS_GOOD_PACKAGING_GROUP]
,TGT.[HAZARDOUS_GOODS_DESCRIPTION] 				=		STG.[HAZARDOUS_GOODS_DESCRIPTION] 	
,TGT.[ITEM_PRICE] 								=		TRIM(REPLACE(STG.[ITEM_PRICE],',','')) 					
,TGT.[STATUS] 									=		STG.[STATUS] 						
,TGT.[TIMESTAMP] 								=		STG.[TIMESTAMP] 					

WHEN NOT MATCHED THEN
INSERT (
[DELIVERY_ITEM_NO] 				
,[DELIVERY_NO] 					
,[TRANSPORT_NO] 					
,[MATERIAL_ID] 					
,[PLANNED_STORAGE_POSITIONS_QTY] 
,[PLANNED_NET_WEIGHT] 			
,[PLANNED_GROSS_WEIGHT] 			
,[PLANNED_VOLUME] 				
,[ACTUAL_STORAGE_POSITIONS_QTY] 	
,[HZG_UN_NO] 					
,[PALLET_INFORMATION] 			
,[BATCH_NO] 						
,[HAZARDOUS_GOODS_INFORMATION] 	
,[HAZARDOUS_GOODS_CLASS] 		
,[PACKAGING_ITEMS_QTY] 			
,[VOLUME_PER_PACKAGE] 			
,[HAZARDOUS_GOOD_PACKAGING_GROUP]
,[HAZARDOUS_GOODS_DESCRIPTION] 	
,[ITEM_PRICE] 					
,[STATUS] 						
,[TIMESTAMP] 
)
VALUES (
STG.[DELIVERY_ITEM_NO] 				
,STG.[DELIVERY_NO] 					
,TRIM(REPLACE(STG.TRANSPORT_NO,'*','')) 					
,STG.[MATERIAL_ID] 					
,TRIM(REPLACE(STG.[PLANNED_STORAGE_POSITIONS_QTY],',',''))  
,TRIM(REPLACE(STG.[PLANNED_NET_WEIGHT],',',''))  			
,TRIM(REPLACE(STG.[PLANNED_GROSS_WEIGHT],',',''))  			
,TRIM(REPLACE(STG.[PLANNED_VOLUME],',',''))  				
,TRIM(REPLACE(STG.[ACTUAL_STORAGE_POSITIONS_QTY] ,',','')) 	
,STG.[HZG_UN_NO] 					
,STG.[PALLET_INFORMATION] 			
,STG.[BATCH_NO] 						
,STG.[HAZARDOUS_GOODS_INFORMATION] 	
,STG.[HAZARDOUS_GOODS_CLASS] 		
,TRIM(REPLACE(STG.[PACKAGING_ITEMS_QTY],',',''))  			
,TRIM(REPLACE(STG.[VOLUME_PER_PACKAGE] ,',','')) 			
,STG.[HAZARDOUS_GOOD_PACKAGING_GROUP]
,STG.[HAZARDOUS_GOODS_DESCRIPTION] 	
,TRIM(REPLACE(STG.[ITEM_PRICE],',',''))  					
,STG.[STATUS] 						
,STG.[TIMESTAMP])

WHEN NOT MATCHED BY SOURCE THEN DELETE;	

END

BEGIN

MERGE TRANSPOREON_TMS.TRANSPORT_FACT_TBL AS TGT
USING
TRANSPOREON_TMS.TRANSPORT_FACT_STG AS STG
ON
TRIM(REPLACE(TGT.TRANSPORT_NO,'*',''))  	= 		TRIM(REPLACE(STG.TRANSPORT_NO,'*',''))
WHEN MATCHED AND 
TGT.[STATUS] 				<> 		STG.[STATUS] OR 
TGT.[TIMESTAMP]    			<>		STG.[TIMESTAMP] OR
TGT.[SHIPMENT_STATUS_ID] 	<>		STG.[SHIPMENT_STATUS_ID]
THEN UPDATE SET	
 TGT.[SAP_SHIPMENT_NO] 							=			STG.[SAP_SHIPMENT_NO] 	
,TGT.[CARRIER_CREDITOR_NO] 						=			STG.[CARRIER_CREDITOR_NO] 
,TGT.[SELECTED_OFFER] 							=			STG.[SELECTED_OFFER] 					
,TGT.[SELECTED_OFFER_CURRENCY_CODE] 			=			STG.[SELECTED_OFFER_CURRENCY_CODE] 		
,TGT.[CARRIER_WHO_PLACED_AN_OFFER] 				=			STG.[CARRIER_WHO_PLACED_AN_OFFER] 		
,TGT.[OFFER] 									=			STG.[OFFER] 							
,TGT.[OFFER_CURRENCY_CODE] 						=			STG.[OFFER_CURRENCY_CODE] 				
,TGT.[OFFER_COMMENT] 							=			STG.[OFFER_COMMENT] 					
,TGT.[ORIGINAL_CURRENCY_CODE] 					=			STG.[ORIGINAL_CURRENCY_CODE] 			
,TGT.[DISTANCE] 								=			STG.[DISTANCE] 							
,TGT.[DISTANCE_UOM_ID] 							=			STG.[DISTANCE_UOM_ID] 					
,TGT.[TRANSPORT_REFERENCE_PRICE] 				=			STG.[TRANSPORT_REFERENCE_PRICE] 		
,TGT.[BASIC_AGREEMENT_PRICE_IN_EUR] 			=			STG.[BASIC_AGREEMENT_PRICE_IN_EUR] 		
,TGT.[TRANSPORT_ASSIGNED_DATE_ID] 				=			STG.[TRANSPORT_ASSIGNED_DATE_ID] 		
,TGT.[TRANSPORT_ASSIGNED_TIME_ID] 				=			STG.[TRANSPORT_ASSIGNED_TIME_ID] 		
,TGT.[OFFER_REQUESTED_DATE] 					=			STG.[OFFER_REQUESTED_DATE] 				
,TGT.[OFFER_REQUESTED_TIME] 					=			STG.[OFFER_REQUESTED_TIME] 				
,TGT.[TRANSPOREON_ID] 							=			STG.[TRANSPOREON_ID] 					
,TGT.[TRANSP_REF_PRICE_CURRENCY_CODE] 			=			STG.[TRANSP_REF_PRICE_CURRENCY_CODE] 	
,TGT.[TRANSPORT_STATUS_DESC] 					=			STG.[TRANSPORT_STATUS_DESC] 			
,TGT.[SHIPPER_SCHEDULER_ASSIGNER] 				=			STG.[SHIPPER_SCHEDULER_ASSIGNER] 		
,TGT.[SHIPPER_SCHEDULER_REQUESTOR] 				=			STG.[SHIPPER_SCHEDULER_REQUESTOR] 		
,TGT.[TRANSPORT_SYSTEM_DATESTAMP_ID] 			=			STG.[TRANSPORT_SYSTEM_DATESTAMP_ID] 	
,TGT.[TRANSPORT_SYSTEM_TIMESTAMP_ID] 			=			STG.[TRANSPORT_SYSTEM_TIMESTAMP_ID] 	
,TGT.[ASSIGNMENT_MODE] 							=			STG.[ASSIGNMENT_MODE] 					
,TGT.[VEHICLE_TYPE_CODE] 						=			STG.[VEHICLE_TYPE_CODE] 				
,TGT.[WEIGHT_UOM_ID] 							=			STG.[WEIGHT_UOM_ID] 					
,TGT.[VOLUME_UOM_ID] 							=			STG.[VOLUME_UOM_ID] 					
,TGT.[SCHEDULING_UNIT_DESC] 					=			STG.[SCHEDULING_UNIT_DESC] 				
,TGT.[STORAGE_POSITIONS_TOTAL_QTY] 				=			TRIM(REPLACE(STG.[STORAGE_POSITIONS_TOTAL_QTY],',',''))	
,TGT.[TOTAL_NO_OF_DELIVERIES] 					=			TRIM(REPLACE(STG.[TOTAL_NO_OF_DELIVERIES],',','')) 		
,TGT.[WEIGHT] 									=			TRIM(REPLACE(STG.[WEIGHT],',','')) 						
,TGT.[VOLUME] 									=			TRIM(REPLACE(STG.[VOLUME] ,',',''))						
,TGT.[LENGTH] 									=			TRIM(REPLACE(STG.[LENGTH],',','')) 						
,TGT.[MOBILE_ORDER_MANAGEMENT_IND] 				=			STG.[MOBILE_ORDER_MANAGEMENT_IND] 		
,TGT.[INTERNAL_TRANSPORT_COMMENT] 				=			STG.[INTERNAL_TRANSPORT_COMMENT] 		
,TGT.[LENGTH_UOM_ID] 							=			STG.[LENGTH_UOM_ID] 					
,TGT.[CO2_EMISSION] 							=			STG.[CO2_EMISSION] 						
,TGT.[TRANSPORT_COMMENT] 						=			STG.[TRANSPORT_COMMENT] 				
,TGT.[TRANSPORT_LICENCE_NO] 					=			STG.[TRANSPORT_LICENCE_NO] 				
,TGT.[ACTUAL_SHIPMENT_LOADING_DATE_ID] 			=			STG.[ACTUAL_SHIPMENT_LOADING_DATE_ID] 	
,TGT.[ACTUAL_SHIPMENT_LOADING_TIME_ID] 			=			STG.[ACTUAL_SHIPMENT_LOADING_TIME_ID] 	
,TGT.[RCA] 										=			STG.[RCA] 								
,TGT.[RCA_EXPLANATION] 							=			STG.[RCA_EXPLANATION] 					
,TGT.[TRANSPORT_UNIT_CODE] 						=			STG.[TRANSPORT_UNIT_CODE] 				
,TGT.[SHIPMENT_STATUS_ID] 						=			STG.[SHIPMENT_STATUS_ID] 				
,TGT.[FULL_LOAD_IND] 							=			STG.[FULL_LOAD_IND] 					
,TGT.[PLANNED_SHIPMENT_LOADING_DATE_ID] 		=			STG.[PLANNED_SHIPMENT_LOADING_DATE_ID] 	
,TGT.[PLANNED_SHIPMENT_LOADING_TIME_ID] 		=			STG.[PLANNED_SHIPMENT_LOADING_TIME_ID] 	
,TGT.[SHIPMENT_TYPE_CODE] 						=			STG.[SHIPMENT_TYPE_CODE] 				
,TGT.[SURCHARGE_1] 								=			STG.[SURCHARGE_1] 						
,TGT.[SURCHARGE_2] 								=			STG.[SURCHARGE_2] 						
,TGT.[SURCHARGE_3] 								=			STG.[SURCHARGE_3] 						
,TGT.[SURCHARGE_2_DESCRIPTION] 					=			STG.[SURCHARGE_2_DESCRIPTION] 			
,TGT.[SURCHARGE_3_DESCRIPTION] 					=			STG.[SURCHARGE_3_DESCRIPTION] 			
,TGT.[SHIPPER_REFERENCE_NO] 					=			STG.[SHIPPER_REFERENCE_NO] 				
,TGT.[TRANSP_ASSGNMT_COMPLETED_DATE_ID] 		=			STG.[TRANSP_ASSGNMT_COMPLETED_DATE_ID] 	
,TGT.[TRANSP_ASSGNMT_COMPLETED_TIME_ID] 		=			STG.[TRANSP_ASSGNMT_COMPLETED_TIME_ID] 	
,TGT.[SURCHARGE_1_DESCRIPTION] 					=			STG.[SURCHARGE_1_DESCRIPTION] 			
,TGT.[TRANSPORT_ADDED_BY_SCHEDULER] 			=			STG.[TRANSPORT_ADDED_BY_SCHEDULER] 		
,TGT.[ASSIGNED_CARRIER_NAME] 					=			STG.[ASSIGNED_CARRIER_NAME] 			
,TGT.[CONTAINER_TYPE_DESC] 						=			STG.[CONTAINER_TYPE_DESC] 				
,TGT.[ORIGINAL_DELIVERIES] 						=			TRIM(REPLACE(STG.[ORIGINAL_DELIVERIES],',','')) 			
,TGT.[ORIG_PLANNED_SHIPMNT_LOAD_DATE] 			=			STG.[ORIG_PLANNED_SHIPMNT_LOAD_DATE] 	 	
,TGT.[ORIGINAL_STORAGE_POSITION] 				=			TRIM(REPLACE(STG.[ORIGINAL_STORAGE_POSITION],',','')) 		
,TGT.[ORIGINAL_VOLUME] 							=			TRIM(REPLACE(STG.[ORIGINAL_VOLUME],',','')) 				
,TGT.[ORIGINAL_WEIGHT] 							=			TRIM(REPLACE(STG.[ORIGINAL_WEIGHT],',','')) 				
,TGT.[UPDATED_SHIPMENT_LOAD_DATE] 				=			STG.[UPDATED_SHIPMENT_LOAD_DATE] 		
,TGT.[ORIG_ACTUAL_SHIPMENT_LOAD_DATE] 			=			STG.[ORIG_ACTUAL_SHIPMENT_LOAD_DATE] 	
,TGT.[ORIGINAL_DELIVERY_NUMBERS] 				=			STG.[ORIGINAL_DELIVERY_NUMBERS] 		
,TGT.[ORIGINAL_VOLUME_UOM_ID] 					=			STG.[ORIGINAL_VOLUME_UOM_ID] 
,TGT.[TIMESTAMP] 								=			STG.[TIMESTAMP] 										
						
WHEN NOT MATCHED BY TARGET
THEN INSERT (
[TRANSPORT_NO] 						
,[SAP_SHIPMENT_NO] 					
,[CARRIER_CREDITOR_NO] 				
,[SELECTED_OFFER] 					
,[SELECTED_OFFER_CURRENCY_CODE] 		
,[CARRIER_WHO_PLACED_AN_OFFER] 		
,[OFFER] 							
,[OFFER_CURRENCY_CODE] 				
,[OFFER_COMMENT] 					
,[ORIGINAL_CURRENCY_CODE] 			
,[DISTANCE] 							
,[DISTANCE_UOM_ID] 					
,[TRANSPORT_REFERENCE_PRICE] 		
,[BASIC_AGREEMENT_PRICE_IN_EUR] 		
,[TRANSPORT_ASSIGNED_DATE_ID] 		
,[TRANSPORT_ASSIGNED_TIME_ID] 		
,[OFFER_REQUESTED_DATE] 				
,[OFFER_REQUESTED_TIME] 				
,[TRANSPOREON_ID] 					
,[TRANSP_REF_PRICE_CURRENCY_CODE] 	
,[TRANSPORT_STATUS_DESC] 			
,[SHIPPER_SCHEDULER_ASSIGNER] 		
,[SHIPPER_SCHEDULER_REQUESTOR] 		
,[TRANSPORT_SYSTEM_DATESTAMP_ID] 	
,[TRANSPORT_SYSTEM_TIMESTAMP_ID] 	
,[ASSIGNMENT_MODE] 					
,[VEHICLE_TYPE_CODE] 				
,[WEIGHT_UOM_ID] 					
,[VOLUME_UOM_ID] 					
,[SCHEDULING_UNIT_DESC] 				
,[STORAGE_POSITIONS_TOTAL_QTY] 		
,[TOTAL_NO_OF_DELIVERIES] 			
,[WEIGHT] 							
,[VOLUME] 							
,[LENGTH] 							
,[MOBILE_ORDER_MANAGEMENT_IND] 		
,[INTERNAL_TRANSPORT_COMMENT] 		
,[LENGTH_UOM_ID] 					
,[CO2_EMISSION] 						
,[TRANSPORT_COMMENT] 				
,[TRANSPORT_LICENCE_NO] 				
,[ACTUAL_SHIPMENT_LOADING_DATE_ID] 	
,[ACTUAL_SHIPMENT_LOADING_TIME_ID] 	
,[RCA] 								
,[RCA_EXPLANATION] 					
,[TRANSPORT_UNIT_CODE] 				
,[SHIPMENT_STATUS_ID] 				
,[FULL_LOAD_IND] 					
,[PLANNED_SHIPMENT_LOADING_DATE_ID] 	
,[PLANNED_SHIPMENT_LOADING_TIME_ID] 	
,[SHIPMENT_TYPE_CODE] 				
,[SURCHARGE_1] 						
,[SURCHARGE_2] 						
,[SURCHARGE_3] 						
,[SURCHARGE_2_DESCRIPTION] 			
,[SURCHARGE_3_DESCRIPTION] 			
,[SHIPPER_REFERENCE_NO] 				
,[TRANSP_ASSGNMT_COMPLETED_DATE_ID] 	
,[TRANSP_ASSGNMT_COMPLETED_TIME_ID] 	
,[SURCHARGE_1_DESCRIPTION] 			
,[TRANSPORT_ADDED_BY_SCHEDULER] 		
,[ASSIGNED_CARRIER_NAME] 			
,[CONTAINER_TYPE_DESC] 				
,[ORIGINAL_DELIVERIES] 				
,[ORIG_PLANNED_SHIPMNT_LOAD_DATE] 	
,[ORIGINAL_STORAGE_POSITION] 		
,[ORIGINAL_VOLUME] 					
,[ORIGINAL_WEIGHT] 					
,[UPDATED_SHIPMENT_LOAD_DATE] 		
,[ORIG_ACTUAL_SHIPMENT_LOAD_DATE] 	
,[ORIGINAL_DELIVERY_NUMBERS] 		
,[ORIGINAL_VOLUME_UOM_ID] 			
,[STATUS] 							
,[TIMESTAMP] 						
)
VALUES(
TRIM(REPLACE(STG.TRANSPORT_NO,'*','')) 						
,STG.[SAP_SHIPMENT_NO] 					
,STG.[CARRIER_CREDITOR_NO] 				
,STG.[SELECTED_OFFER] 					
,STG.[SELECTED_OFFER_CURRENCY_CODE] 		
,STG.[CARRIER_WHO_PLACED_AN_OFFER] 		
,STG.[OFFER] 							
,STG.[OFFER_CURRENCY_CODE] 				
,STG.[OFFER_COMMENT] 					
,STG.[ORIGINAL_CURRENCY_CODE] 			
,TRIM(REPLACE(STG.[DISTANCE],',','')) 							
,STG.[DISTANCE_UOM_ID] 					
,STG.[TRANSPORT_REFERENCE_PRICE] 		
,STG.[BASIC_AGREEMENT_PRICE_IN_EUR] 		
,STG.[TRANSPORT_ASSIGNED_DATE_ID] 		
,STG.[TRANSPORT_ASSIGNED_TIME_ID] 		
,STG.[OFFER_REQUESTED_DATE] 				
,STG.[OFFER_REQUESTED_TIME] 				
,STG.[TRANSPOREON_ID] 					
,STG.[TRANSP_REF_PRICE_CURRENCY_CODE] 	
,STG.[TRANSPORT_STATUS_DESC] 			
,STG.[SHIPPER_SCHEDULER_ASSIGNER] 		
,STG.[SHIPPER_SCHEDULER_REQUESTOR] 		
,STG.[TRANSPORT_SYSTEM_DATESTAMP_ID] 	
,STG.[TRANSPORT_SYSTEM_TIMESTAMP_ID] 	
,STG.[ASSIGNMENT_MODE] 					
,STG.[VEHICLE_TYPE_CODE] 				
,STG.[WEIGHT_UOM_ID] 					
,STG.[VOLUME_UOM_ID] 					
,STG.[SCHEDULING_UNIT_DESC] 				
,TRIM(REPLACE(STG.[STORAGE_POSITIONS_TOTAL_QTY],',','')) 		
,TRIM(REPLACE(STG.[TOTAL_NO_OF_DELIVERIES],',','')) 			
,TRIM(REPLACE(STG.[WEIGHT],',','')) 							
,TRIM(REPLACE(STG.[VOLUME] ,',',''))							
,TRIM(REPLACE(STG.[LENGTH],',','')) 							
,STG.[MOBILE_ORDER_MANAGEMENT_IND] 		
,STG.[INTERNAL_TRANSPORT_COMMENT] 		
,STG.[LENGTH_UOM_ID] 					
,STG.[CO2_EMISSION] 						
,STG.[TRANSPORT_COMMENT] 				
,STG.[TRANSPORT_LICENCE_NO] 				
,STG.[ACTUAL_SHIPMENT_LOADING_DATE_ID] 	
,STG.[ACTUAL_SHIPMENT_LOADING_TIME_ID] 	
,STG.[RCA] 								
,STG.[RCA_EXPLANATION] 					
,STG.[TRANSPORT_UNIT_CODE] 				
,STG.[SHIPMENT_STATUS_ID] 				
,STG.[FULL_LOAD_IND] 					
,STG.[PLANNED_SHIPMENT_LOADING_DATE_ID] 	
,STG.[PLANNED_SHIPMENT_LOADING_TIME_ID] 	
,STG.[SHIPMENT_TYPE_CODE] 				
,STG.[SURCHARGE_1] 						
,STG.[SURCHARGE_2] 						
,STG.[SURCHARGE_3] 						
,STG.[SURCHARGE_2_DESCRIPTION] 			
,STG.[SURCHARGE_3_DESCRIPTION] 			
,STG.[SHIPPER_REFERENCE_NO] 				
,STG.[TRANSP_ASSGNMT_COMPLETED_DATE_ID] 	
,STG.[TRANSP_ASSGNMT_COMPLETED_TIME_ID] 	
,STG.[SURCHARGE_1_DESCRIPTION] 			
,STG.[TRANSPORT_ADDED_BY_SCHEDULER] 		
,STG.[ASSIGNED_CARRIER_NAME] 			
,STG.[CONTAINER_TYPE_DESC] 				
,TRIM(REPLACE(STG.[ORIGINAL_DELIVERIES],',','')) 				
,STG.[ORIG_PLANNED_SHIPMNT_LOAD_DATE] 	
,TRIM(REPLACE(STG.[ORIGINAL_STORAGE_POSITION],',','')) 		
,TRIM(REPLACE(STG.[ORIGINAL_VOLUME],',','')) 					
,TRIM(REPLACE(STG.[ORIGINAL_WEIGHT],',','')) 					
,STG.[UPDATED_SHIPMENT_LOAD_DATE] 		
,STG.[ORIG_ACTUAL_SHIPMENT_LOAD_DATE] 	
,STG.[ORIGINAL_DELIVERY_NUMBERS] 		
,STG.[ORIGINAL_VOLUME_UOM_ID] 			
,STG.[STATUS] 							
,STG.[TIMESTAMP] 						
)

WHEN NOT MATCHED BY SOURCE THEN DELETE;	

END

BEGIN

MERGE TRANSPOREON_TMS.TRANSPORT_VISIBILITY_FACT_TBL AS TGT
USING
TRANSPOREON_TMS.TRANSPORT_VISIBILITY_FACT_STG AS STG
ON
TGT.[DELIVERY_NO]  								= 			STG.[DELIVERY_NO]
AND TRIM(REPLACE(TGT.TRANSPORT_NO,'*','')) 		=			TRIM(REPLACE(STG.TRANSPORT_NO,'*',''))
AND TGT.[TRANSP_VISIBILITY_STATUS_DESC] 		=			STG.[TRANSP_VISIBILITY_STATUS_DESC]
WHEN MATCHED AND 
TGT.[STATUS] 		<> 	STG.[STATUS] OR 
TGT.[TIMESTAMP]   	<>	STG.[TIMESTAMP]
THEN UPDATE SET 									
 TGT.[STATUS_PLACED_MANUAL_DATE_STAMP_ID]			=			STG.[STATUS_PLACED_MANUAL_DATE_STAMP_ID]
,TGT.[STATUS_PLACED_SYS_DATE_STAMP_ID] 				=			STG.[STATUS_PLACED_SYS_DATE_STAMP_ID] 	
,TGT.[STATUS_PLACED_SYS_TIME_STAMP_ID] 				=			STG.[STATUS_PLACED_SYS_TIME_STAMP_ID] 	
,TGT.[STATUS_PLACED_MANUAL_TIME_STAMP_ID]			=			STG.[STATUS_PLACED_MANUAL_TIME_STAMP_ID]
,TGT.[COMPANY_NAME] 								=			STG.[COMPANY_NAME] 						
,TGT.[STATUS] 										=			STG.[STATUS] 							
,TGT.[TIMESTAMP] 									=			STG.[TIMESTAMP] 						
													
WHEN NOT MATCHED THEN
INSERT (
[DELIVERY_NO] 										
,[TRANSPORT_NO] 						
,[TRANSP_VISIBILITY_STATUS_DESC] 		
,[STATUS_PLACED_MANUAL_DATE_STAMP_ID]	
,[STATUS_PLACED_SYS_DATE_STAMP_ID] 		
,[STATUS_PLACED_SYS_TIME_STAMP_ID] 		
,[STATUS_PLACED_MANUAL_TIME_STAMP_ID]	
,[COMPANY_NAME] 						
,[STATUS] 								
,[TIMESTAMP] 							
)
VALUES
(
 STG.[DELIVERY_NO] 							
,TRIM(REPLACE(STG.TRANSPORT_NO,'*','')) 						
,STG.[TRANSP_VISIBILITY_STATUS_DESC] 		
,STG.[STATUS_PLACED_MANUAL_DATE_STAMP_ID]	
,STG.[STATUS_PLACED_SYS_DATE_STAMP_ID] 		
,STG.[STATUS_PLACED_SYS_TIME_STAMP_ID] 		
,STG.[STATUS_PLACED_MANUAL_TIME_STAMP_ID]	
,STG.[COMPANY_NAME] 						
,STG.[STATUS] 								
,STG.[TIMESTAMP] 
)

WHEN NOT MATCHED BY SOURCE THEN DELETE;

END		

END
