CREATE TABLE [TRANSPOREON_TMS].[CARRIER_SURCHARGE_FACT] (
    [DELIVERY_NO]                   NUMERIC (20)  NOT NULL,
    [TRANSPORT_NO]                  VARCHAR (50)  NULL,
    [SURCHARGE_ID]                  BIGINT        NOT NULL,
    [SURCHARGE_SYSTEM_DATESTAMP_ID] BIGINT        NULL,
    [SURCHARGE_SYSTEM_TIMESTAMP_ID] BIGINT        NULL,
    [SURCHARGE_PRICE]               VARCHAR (50)  NULL,
    [SURCHARGE_CURRENCY_CODE]       VARCHAR (5)   NULL,
    [SURCHARGE_DESC]                VARCHAR (MAX) COLLATE Latin1_General_100_CI_AI_SC_UTF8 NULL,
    [SURCHARGE_STATUS_ID]           BIGINT        NULL,
    [SURCHARGE_NAME]                VARCHAR (100) NULL,
    [COMPANY_NAME]                  VARCHAR (MAX) NULL,
    [REASON_DESC]                   VARCHAR (MAX) COLLATE Latin1_General_100_CI_AI_SC_UTF8 NULL,
    [SURCHARGE_LEVEL_DESC]          VARCHAR (50)  NULL,
    [STATUS]                        VARCHAR (5)   NULL,
    [TIMESTAMP]                     DATETIME      NOT NULL,
    CONSTRAINT [PK_CARRIER_SURCHARGE_FACT] PRIMARY KEY CLUSTERED ([DELIVERY_NO] ASC, [SURCHARGE_ID] ASC),
    CONSTRAINT [FK_SURCHARGE_SYSTEM_DATESTAMP] FOREIGN KEY ([SURCHARGE_SYSTEM_DATESTAMP_ID]) REFERENCES [COMMON_DIMENSIONS].[DATE_DIM] ([DATE_ID]),
    CONSTRAINT [FK_SURCHARGE_SYSTEM_TIMESTAMP] FOREIGN KEY ([SURCHARGE_SYSTEM_TIMESTAMP_ID]) REFERENCES [COMMON_DIMENSIONS].[TIME_DIM] ([TIME_ID])
);

