CREATE TABLE [TRANSPOREON_TMS].[DELIVERY_ITEM_FACT] (
    [DELIVERY_ITEM_NO]               INT           NOT NULL,
    [DELIVERY_NO]                    NUMERIC (20)  NOT NULL,
    [TRANSPORT_NO]                   VARCHAR (100) NULL,
    [MATERIAL_ID]                    BIGINT        NULL,
    [PLANNED_STORAGE_POSITIONS_QTY]  VARCHAR (50)  NULL,
    [PLANNED_NET_WEIGHT]             VARCHAR (50)  NULL,
    [PLANNED_GROSS_WEIGHT]           VARCHAR (50)  NULL,
    [PLANNED_VOLUME]                 VARCHAR (50)  NULL,
    [ACTUAL_STORAGE_POSITIONS_QTY]   VARCHAR (50)  NULL,
    [HZG_UN_NO]                      VARCHAR (50)  NULL,
    [PALLET_INFORMATION]             VARCHAR (MAX) NULL,
    [BATCH_NO]                       VARCHAR (50)  NULL,
    [HAZARDOUS_GOODS_INFORMATION]    VARCHAR (MAX) COLLATE Latin1_General_100_CI_AI_SC_UTF8 NULL,
    [HAZARDOUS_GOODS_CLASS]          VARCHAR (10)  NULL,
    [PACKAGING_ITEMS_QTY]            VARCHAR (50)  NULL,
    [VOLUME_PER_PACKAGE]             VARCHAR (50)  NULL,
    [HAZARDOUS_GOOD_PACKAGING_GROUP] VARCHAR (10)  NULL,
    [HAZARDOUS_GOODS_DESCRIPTION]    VARCHAR (MAX) COLLATE Latin1_General_100_CI_AI_SC_UTF8 NULL,
    [ITEM_PRICE]                     VARCHAR (50)  NULL,
    [STATUS]                         VARCHAR (5)   NULL,
    [TIMESTAMP]                      DATETIME      NULL
);

