CREATE TABLE [TRANSPOREON_TMS].[TRANSPORT_VISIBILITY_FACT_STG] (
    [DELIVERY_NO]                        NUMERIC (20)  NOT NULL,
    [TRANSPORT_NO]                       VARCHAR (50)  NOT NULL,
    [TRANSP_VISIBILITY_STATUS_DESC]      VARCHAR (150) NOT NULL,
    [STATUS_PLACED_MANUAL_DATE_STAMP_ID] BIGINT        NULL,
    [STATUS_PLACED_SYS_DATE_STAMP_ID]    BIGINT        NULL,
    [STATUS_PLACED_SYS_TIME_STAMP_ID]    BIGINT        NULL,
    [STATUS_PLACED_MANUAL_TIME_STAMP_ID] BIGINT        NULL,
    [COMPANY_NAME]                       VARCHAR (150) COLLATE Latin1_General_100_CI_AI_SC_UTF8 NULL,
    [STATUS]                             VARCHAR (5)   NULL,
    [TIMESTAMP]                          DATETIME      NULL
);

